### ISSUE TITLE
Device rotation issues

### ISSUE THREAD

**Issue by yanush** [react-native-community/react-native-modal#27]
I've encountered two issues while using this component over the regular modal:
1. I had to add supportedOrientations={['portrait', 'landscape']} prop in order for rotation to actually work (which is not documented anywhere).
2. After doing so, and rotating the device, the black background isn't covering the entire screen anymore

**Comment by mmazzarolo** [comment]
Hello @yanush 

>I had to add supportedOrientations={['portrait', 'landscape']} prop in order for rotation to actually work (which is not documented anywhere).  

It is not documented because it's the first time I hear about it 😺: it is a react-native modal prop that wasn't available when I first created [this repo](http://facebook.github.io/react-native/releases/0.44/docs/modal.html#supportedorientations). 
 
I'll investigate a bit on it.

**Comment by annelorraineuy** [comment]
> After doing so, and rotating the device, the black background isn't covering the entire screen anymore

I see the same bug. My modal is in the center but the black overlay is cut off switching from Portrait to Landscape.

**Comment by annelorraineuy** [comment]
I didn't need to put `supportedOrientations={['portrait', 'landscape']}` in order for my modal to rotate though.

**Comment by mmazzarolo** [comment]
I think I'll should add a listener on `didUpdateDimensions` instead of using the `onLayout`. 
[It has always been hard handling modal's rotation on react-native](https://github.com/facebook/react-native/issues/7708).  

I'll publish a fix in the next few hours, will someone test it if I publish it on the master branch? :)

**Comment by annelorraineuy** [comment]
I can test it! :)

**Comment by annelorraineuy** [comment]
I think I was able to fix it. In `index.styles.js`,
```
backdrop: {
    flex: 1,
    position: 'absolute',
    top: 0,
    ....
  },
```
@mmazzarolo

**Comment by annelorraineuy** [comment]
But it's probably worth  adding a listener as you suggested, since it was reported that the modal is not centered in some android devices.

**Comment by mmazzarolo** [comment]
Thank you for the PR!  
Could you try the update i pushed into master and see if it works correctly for you?  
It should be a "cleaner" solution because it handles the device rotation correctly, while the `onLayout` didn't work at all (probably because of a recent react-native release I guess 🤔 ).  

Anyway, I tested it on an iPhone 6 simulator providing `supportedOrientations={['portrait', 'landscape']}` as prop and it worked fine.  

Let me know if it works for you, otherwise I'll take a look at your PR and merge it :) 
(Actually I'mg going to bed right now, I'll take a look at it tomorrow).

**Comment by annelorraineuy** [comment]
@mmazzarolo I'm testing on Android. I get an exception that says `undefined is not an objet (evaluating 'dimensionsUpdate.window.width` in `_handleDimensionsUpdate` : ( and the black overlay still isn't covering the whole screen.

**Comment by mmazzarolo** [comment]
😞 
I'll have to wait for the weekend to test in on Android.  
Anyway, I shipped another small tweak on the master branch as a last resort, may you give it a try? 

Thank you!

**Comment by annelorraineuy** [comment]
@mmazzarolo Tested on Android, DEV === false.  so the black overlay does cover the whole screen, but on a Samsung Tab A it takes a split second to readjust and stretch out the overlay (either Portrait to Landscape or Landscape to Portrait). I assume this flash will not be seen in iOS but on Android devices like the Samsung Tab A unfortunately it is apparent. :(

**Comment by annelorraineuy** [comment]
P.S. The PR I submitted also results in a flash but quicker. I guess coz setting `flex:1` is faster than retrieving device dimensions.

**Comment by mmazzarolo** [comment]
@annelorraineuy, thank you for testing it, I appreciate it 👍 
On iOS it works fine indeed, I'll test it soon on a Nexus5X and I'll check how much the delay lasts.

**Comment by mmazzarolo** [comment]
I've just been able to test it on a Nexus5 in both DEV and PROD mode and the transition is flawless.  
@yanush could you give it a try too?
